/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Clases.CalculosMatematicos;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Asignacion_CalculosMatematicos extends javax.swing.JFrame {

    /**
     * Creates new form Asignacion_CalculosMatematicos
     */
    public Asignacion_CalculosMatematicos() {
        initComponents();
        
        
         //position View
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtApe = new javax.swing.JTextField();
        BtnResta = new javax.swing.JToggleButton();
        BtnReg = new javax.swing.JToggleButton();
        BtnLimpiar = new javax.swing.JToggleButton();
        BtnSuma = new javax.swing.JToggleButton();
        btnMult = new javax.swing.JToggleButton();
        BtnDiv = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setText("C A L C U L O S    M A T E M A T I C O S");

        jLabel2.setText("Numero 1");

        jLabel3.setText("Numero 2");

        txtApe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApeActionPerformed(evt);
            }
        });

        BtnResta.setBackground(new java.awt.Color(255, 102, 102));
        BtnResta.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        BtnResta.setText("R E S T A R");
        BtnResta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestaActionPerformed(evt);
            }
        });

        BtnReg.setBackground(new java.awt.Color(255, 0, 51));
        BtnReg.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        BtnReg.setText("R e g r e s a r");
        BtnReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegActionPerformed(evt);
            }
        });

        BtnLimpiar.setBackground(new java.awt.Color(255, 102, 102));
        BtnLimpiar.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        BtnLimpiar.setText("Limpiar Campos");
        BtnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        BtnSuma.setBackground(new java.awt.Color(255, 102, 102));
        BtnSuma.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        BtnSuma.setText("S U M A R");
        BtnSuma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumaActionPerformed(evt);
            }
        });

        btnMult.setBackground(new java.awt.Color(255, 102, 102));
        btnMult.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        btnMult.setText("M U L T I P L I C A R");
        btnMult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultActionPerformed(evt);
            }
        });

        BtnDiv.setBackground(new java.awt.Color(255, 102, 102));
        BtnDiv.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        BtnDiv.setText("D I V I D I R");
        BtnDiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMult)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApe, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BtnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(BtnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMult, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(BtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(BtnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Método para verificar si los campos están diligenciados
    private boolean camposDiligenciados() {
        return !txtnom.getText().isEmpty()
                && !txtApe.getText().isEmpty();
                
    }

    
    //Metodo para el btn resta
    private void BtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestaActionPerformed

         // Validación de formulario diligenciado
        if (camposDiligenciados()) {
            // Generamos Variables y obtenemos la información ingresada en los campos de la vista
            int Num1 = Integer.parseInt(this.txtnom.getText());
            int Num2 = Integer.parseInt(this.txtApe.getText());
            
            //Se crea una instancia de la clase Calculos matematicos
            CalculosMatematicos Obj;
            Obj = new CalculosMatematicos(Num1, Num2);
            Obj.Resta();
             
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.");
        }

    }//GEN-LAST:event_BtnRestaActionPerformed

    private void BtnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegActionPerformed
        // TODO add your handling code here:
        dispose();
        AsignacionesMenu Obj;
        Obj = new AsignacionesMenu();
        Obj.setVisible(true);
    }//GEN-LAST:event_BtnRegActionPerformed

    //metodo para Limpiar Campos
    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        // TODO add your handling code here:
        this.txtnom.setText("");
        this.txtApe.setText("");
   
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void txtApeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApeActionPerformed

    
    //Metodo para activar el boton de sumar
    private void BtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumaActionPerformed
         // Validación de formulario diligenciado
        if (camposDiligenciados()) {
            // Generamos Variables y obtenemos la información ingresada en los campos de la vista
            int Num1 = Integer.parseInt(this.txtnom.getText());
            int Num2 = Integer.parseInt(this.txtApe.getText());
            
            //Se crea una instancia de la clase Calculos matematicos
            CalculosMatematicos Obj;
            Obj = new CalculosMatematicos(Num1, Num2);
            Obj.Suma();
             
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.");
        }
        
    }//GEN-LAST:event_BtnSumaActionPerformed

    
    //metodo para el btn multiplicar
    private void btnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultActionPerformed
        // TODO add your handling code here:
        // Validación de formulario diligenciado
        if (camposDiligenciados()) {
            // Generamos Variables y obtenemos la información ingresada en los campos de la vista
            int Num1 = Integer.parseInt(this.txtnom.getText());
            int Num2 = Integer.parseInt(this.txtApe.getText());
            
            //Se crea una instancia de la clase Calculos matematicos
            CalculosMatematicos Obj;
            Obj = new CalculosMatematicos(Num1, Num2);
            Obj.Multiplicar();
             
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.");
        }
    }//GEN-LAST:event_btnMultActionPerformed

    
    //metodo para el btn dividir
    private void BtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDivActionPerformed
        // TODO add your handling code here:
        
         // Validación de formulario diligenciado
        if (camposDiligenciados()) {
            // Generamos Variables y obtenemos la información ingresada en los campos de la vista
            int Num1 = Integer.parseInt(this.txtnom.getText());
            int Num2 = Integer.parseInt(this.txtApe.getText());
            
            //Se crea una instancia de la clase Calculos matematicos
            CalculosMatematicos Obj;
            Obj = new CalculosMatematicos(Num1, Num2);
            Obj.Dividir();
            
             
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.");
        }
    }//GEN-LAST:event_BtnDivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asignacion_CalculosMatematicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asignacion_CalculosMatematicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asignacion_CalculosMatematicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asignacion_CalculosMatematicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asignacion_CalculosMatematicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnDiv;
    private javax.swing.JToggleButton BtnLimpiar;
    private javax.swing.JToggleButton BtnReg;
    private javax.swing.JToggleButton BtnResta;
    private javax.swing.JToggleButton BtnSuma;
    private javax.swing.JToggleButton btnMult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApe;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
}
